In [18]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing

In [19]:
train_data = np.genfromtxt("GDpr2_train.csv", delimiter = ",")
X = train_data[:, 0:4]
#scaler = preprocessing.StandardScaler()
#scaler.fit(X)
#X = scaler.transform(X)
Y = train_data[:, 4]
print(X)
print(Y)

[[   8.58   38.38 1021.03   84.37]
 [  21.79   58.2  1017.21   66.74]
 [  16.64   48.92 1011.55   78.76]
 ...
 [  29.8    69.34 1009.36   64.74]
 [  16.37   54.3  1017.94   63.63]
 [  30.11   62.04 1010.69   47.96]]
[482.26 446.94 452.56 ... 437.65 459.97 444.42]


In [20]:
alg1 = LinearRegression()
alg1.fit(X, Y)
print(alg1.coef_)
print(alg1.intercept_)

[-1.99374681 -0.2269919   0.05863744 -0.16016753]
458.21219391683843


In [21]:
test_data = np.genfromtxt("GDpr2_test.csv", delimiter = ",")
X_test = test_data[:, 0:4]
#scaler = preprocessing.StandardScaler()
#scaler.fit(X_test)
#X_test = scaler.transform(X_test)
print(X_test)

[[  11.95   42.03 1017.58   90.89]
 [  12.07   38.25 1012.67   81.66]
 [  26.91   74.99 1005.64   78.98]
 ...
 [  24.32   66.25 1009.09   91.89]
 [  23.49   42.8  1013.96   65.31]
 [  21.76   60.27 1018.96   85.06]]


In [22]:
Y_test = alg1.predict(X_test)
print(Y_test)

[469.95711113 471.76632733 433.85647002 ... 439.13871988 450.65930697
 447.27281902]


In [23]:
np.savetxt("Y_GDProject2_test_predicted.csv", Y_test, fmt = "%0.5f", delimiter=",")