In [51]:
import numpy as np

In [52]:
# for and function
x = np.array([[0, 0], [0, 1], [1, 0], [1,1]])
y = np.array([[0, 0, 0, 1]]).T
x.shape, y.shape

((4, 2), (4, 1))

In [53]:
# sigmoid function
def sig(z):
    return 1 / (1 + np.exp(-z))

In [54]:
# derivative of sigmoid function
def derivativeSig(z):
    return sig(z) * (1 - sig(z))

In [71]:
# for no hidden layer
weights = 2 * np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
lr = 0.1
num_of_iterations = 10000
weights, bias

(array([[-0.08503303],
        [-0.37916862]]), array([0.93018352]))

In [63]:
# forward propagation whith no hidden layer
output0 = x
output = sig(np.dot(output0, weights) + bias)
output

array([[0.29509114],
       [0.14313875],
       [0.23847872],
       [0.11108407]])

In [69]:
for itr in range(num_of_iterations):
    output0 = x
    output = sig(np.dot(output0, weights) + bias)
    first_term = output - y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term
    changes = np.array([[0.0], [0.0]]) # same dimension as weights
    for i in range(2): # for weights
        for j in range(4): # for features
            changes[i][0] += first_two[j][0] * output0[j][i]
    weights = weights - lr * changes
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0] * 1 # bias initial value is always 1
    bias = bias - lr * bias_change
output = sig(np.dot(output0, weights) + bias)
output

array([[2.49024288e-04],
       [5.58441501e-02],
       [5.58441504e-02],
       [9.33532218e-01]])

In [72]:
# removing for loops using vector operation
for itr in range(num_of_iterations):
    output0 = x
    output = sig(np.dot(output0, weights) + bias)
    first_term = output - y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term
    changes = np.dot(output0.T, first_two)
    weights = weights - lr * changes
    bias_change = np.sum(first_two)
    bias = bias - lr * bias_change
output = sig(np.dot(output0, weights) + bias)
output

array([[2.49068349e-04],
       [5.58472418e-02],
       [5.58472420e-02],
       [9.33528514e-01]])

In [7]:
# with 1 hidden layer
wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1
wh, bh, wo, bo

(array([[ 0.66696827, -0.98905007],
        [ 0.76453844,  0.88171894]]),
 array([[ 0.43901882, -0.43775203]]),
 array([[-0.35015857],
        [ 0.04761434]]),
 array([[-0.95496953]]))

In [8]:
output0 = x
output_hidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(output_hidden, wo) + bo)
output

array([[0.24063583],
       [0.23231423],
       [0.22990393],
       [0.22427695]])

# XOR using neural network with hidden layer

In [14]:
import numpy as np

In [15]:
# for XOR
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0, 1, 1, 0]]).T

In [16]:
def sig(z):
    return 1 / (1 + np.exp(-z))

In [17]:
def derivativeSig(z):
    return sig(z) * (1 - sig(z))

In [18]:
# one hidden layer weights
wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1
lr = 0.1

In [19]:
# forward propagation with one hidden layer
for itr in range(10000):
    output0 = x
    inputHidden = np.dot(output0, wh) + bh
    outputHidden = sig(inputHidden)
    input_for_output_layer = np.dot(outputHidden, wo) + bo
    output = sig(input_for_output_layer)

    first_term_output_layer = output - y
    second_term_output_layer = derivativeSig(input_for_output_layer)
    first_two_output_layer = first_term_output_layer * second_term_output_layer

    first_term_hidden_layer = np.dot(first_two_output_layer, wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

    # for finding changes, we use output of previous layer and multiply it with first_two of present layer
    changes_output = np.dot(outputHidden.T, first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer, axis=0, keepdims=True)

    changes_hidden = np.dot(output0.T, first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, axis=0, keepdims=True)

    wo = wo - lr * changes_output
    bo = bo - lr * changes_output_bias
    
    wh = wh - lr * changes_hidden
    bh = bh - lr * changes_hidden_bias

output0 = x
inputHidden = np.dot(output0, wh) + bh
outputHidden = sig(inputHidden)
input_for_output_layer = np.dot(outputHidden, wo) + bo
output = sig(input_for_output_layer)
output, wh, bh, wo, bo

(array([[0.07878795],
        [0.92803473],
        [0.92816798],
        [0.08731997]]), array([[-4.15336117,  6.29965218],
        [-4.14718326,  6.26320585]]), array([[ 6.19610113, -2.70339745]]), array([[6.53414426],
        [6.32000242]]), array([[-9.37651577]]))